services:
  # redis:
  #   container_name: housefy-api-redis
  #   image: redis
  #   command: redis-server
  #   ports:
  #   - 6379:6379

  database:
    container_name: housefy-api-database
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - ${DB_PORT}:5432